version: '3.8'

services:
  web:
    build: ./web_app
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
    
    environment:
      - DB_HOST=db   
      - DB_USER=usuario
      - DB_PASSWORD=12345
      - DB_NAME=nombres

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nombres
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: Rot123
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-pRot123"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  db_data: